openapi: 3.0.0
info:
  title: Epic Movie Quotes
  description: giorgi Surmanidze
  version: 1.0.0
servers:
  - url: http://127.0.0.1:8000/api
    description: local server
  - url: http://giorgi-surmanidze/api
    description: production server
paths:
  /register:
    $ref: "./_swagger/paths/auth.yaml#/paths/~1register"